# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Avenida Cabildo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'Google/SignIn'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'
  pod 'SWRevealViewController'
  pod 'SDWebImage'
  pod 'XLPagerTabStrip'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  # Pods for Avenida Cabildo

  target 'Avenida CabildoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'FBSDKCoreKit'
  	pod 'FBSDKShareKit'
  	pod 'FBSDKLoginKit'
    pod 'Google/SignIn'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'GoogleSignIn'
    pod 'SWRevealViewController'
    pod 'SDWebImage'
    pod 'XLPagerTabStrip'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
  end

  target 'Avenida CabildoUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'FBSDKCoreKit'
  	pod 'FBSDKShareKit'
  	pod 'FBSDKLoginKit'
    pod 'Google/SignIn'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'GoogleSignIn'
    pod 'SWRevealViewController'
    pod 'SDWebImage'
    pod 'XLPagerTabStrip'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
  end


end
